chart_homepage:
    path:     /chart
    defaults: { _controller: chartBundle:Default:chart }
chart_emobile:
    path:     /chartemobile
    defaults: { _controller: chartBundle:Chartemobile:chartemobile }
chart_efixe:
    path:     /chartefixe
    defaults: { _controller: chartBundle:Chartemobile:chartefixe }
chart_ecomputer:
    path:     /chartecomp
    defaults: { _controller: chartBundle:Chartemobile:chartecomputer }
chart_einternet:
    path:     /charteint
    defaults: { _controller: chartBundle:Chartemobile:charteinternet }
chart_dns:
    path:     /chartdns
    defaults: { _controller: chartBundle:Dns:dns}