ictdata_homepage:
    path:     /index
    defaults: { _controller: IctdataBundle:Ictdata:index }
ictdata_grapheMobile:
    path:     /grm
    defaults: { _controller: IctdataBundle:Ictdata:grapheMobile }
ictdata_grapheFixe:
    path:     /grf
    defaults: { _controller: IctdataBundle:Ictdata:grapheFixe }
ictdata_spaceadmin:
    path:     /formenquete
    defaults: { _controller: IctdataBundle:Ictdata:formenquete }
ictdata_parcabonn:
    path:     /form_parcabonn
    defaults: { _controller: IctdataBundle:Ictdata:forme_d_parcabonn }
ictdata_showdata:
    path:     /showdata
    defaults: { _controller: IctdataBundle:Ictdata:showdata }
ictdata_recherche:
    path:     /recherche/{a}/{b}
    defaults: { _controller: IctdataBundle:Ictdata:recherche }