<?php

namespace Proxies\__CG__\Ictdata\IctdataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class D_taux_penetration extends \Ictdata\IctdataBundle\Entity\D_taux_penetration implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tMobilePostPaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tMobilePrePaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tFixe', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tInternet'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tMobilePostPaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tMobilePrePaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tFixe', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_taux_penetration' . "\0" . 'tInternet'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (D_taux_penetration $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTDate($tDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTDate', [$tDate]);

        return parent::setTDate($tDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTDate', []);

        return parent::getTDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setTMobilePostPaye($tMobilePostPaye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTMobilePostPaye', [$tMobilePostPaye]);

        return parent::setTMobilePostPaye($tMobilePostPaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getTMobilePostPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTMobilePostPaye', []);

        return parent::getTMobilePostPaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setTMobilePrePaye($tMobilePrePaye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTMobilePrePaye', [$tMobilePrePaye]);

        return parent::setTMobilePrePaye($tMobilePrePaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getTMobilePrePaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTMobilePrePaye', []);

        return parent::getTMobilePrePaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setTFixe($tFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTFixe', [$tFixe]);

        return parent::setTFixe($tFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getTFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTFixe', []);

        return parent::getTFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTInternet($tInternet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTInternet', [$tInternet]);

        return parent::setTInternet($tInternet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTInternet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTInternet', []);

        return parent::getTInternet();
    }

}
