<?php

namespace Proxies\__CG__\Ictdata\IctdataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class D_revenu_usage extends \Ictdata\IctdataBundle\Entity\D_revenu_usage implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMinuteComMobile', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMensuelClientMobile', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMinuteComFixe', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMensuelComFixe'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMinuteComMobile', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMensuelClientMobile', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMinuteComFixe', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_revenu_usage' . "\0" . 'rMensuelComFixe'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (D_revenu_usage $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRDate($rDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRDate', [$rDate]);

        return parent::setRDate($rDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRDate', []);

        return parent::getRDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRMinuteComMobile($rMinuteComMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRMinuteComMobile', [$rMinuteComMobile]);

        return parent::setRMinuteComMobile($rMinuteComMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getRMinuteComMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRMinuteComMobile', []);

        return parent::getRMinuteComMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setRMensuelClientMobile($rMensuelClientMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRMensuelClientMobile', [$rMensuelClientMobile]);

        return parent::setRMensuelClientMobile($rMensuelClientMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getRMensuelClientMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRMensuelClientMobile', []);

        return parent::getRMensuelClientMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setRMinuteComFixe($rMinuteComFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRMinuteComFixe', [$rMinuteComFixe]);

        return parent::setRMinuteComFixe($rMinuteComFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRMinuteComFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRMinuteComFixe', []);

        return parent::getRMinuteComFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setRMensuelComFixe($rMensuelComFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRMensuelComFixe', [$rMensuelComFixe]);

        return parent::setRMensuelComFixe($rMensuelComFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getRMensuelComFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRMensuelComFixe', []);

        return parent::getRMensuelComFixe();
    }

}
