<?php

namespace Proxies\__CG__\Ictdata\IctdataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class D_infrastruct_autre extends \Ictdata\IctdataBundle\Entity\D_infrastruct_autre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iBpInternet', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrPrestaMaTotal', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrPrestaMaNew', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrLirMarocains', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iParcMarocIpv4Afrinic', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iStockIpv4Afrinic', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrIpv4Allouees', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iRepartIpv4LirMaroc', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iEtatEpuisIpv4', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iPlageIpv6Maroc'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iBpInternet', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrPrestaMaTotal', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrPrestaMaNew', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrLirMarocains', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iParcMarocIpv4Afrinic', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iStockIpv4Afrinic', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iNbrIpv4Allouees', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iRepartIpv4LirMaroc', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iEtatEpuisIpv4', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_infrastruct_autre' . "\0" . 'iPlageIpv6Maroc'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (D_infrastruct_autre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIDate($iDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIDate', [$iDate]);

        return parent::setIDate($iDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDate', []);

        return parent::getIDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIBpInternet($iBpInternet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIBpInternet', [$iBpInternet]);

        return parent::setIBpInternet($iBpInternet);
    }

    /**
     * {@inheritDoc}
     */
    public function getIBpInternet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIBpInternet', []);

        return parent::getIBpInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setINbrPrestaMaTotal($iNbrPrestaMaTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINbrPrestaMaTotal', [$iNbrPrestaMaTotal]);

        return parent::setINbrPrestaMaTotal($iNbrPrestaMaTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getINbrPrestaMaTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINbrPrestaMaTotal', []);

        return parent::getINbrPrestaMaTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setINbrPrestaMaNew($iNbrPrestaMaNew)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINbrPrestaMaNew', [$iNbrPrestaMaNew]);

        return parent::setINbrPrestaMaNew($iNbrPrestaMaNew);
    }

    /**
     * {@inheritDoc}
     */
    public function getINbrPrestaMaNew()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINbrPrestaMaNew', []);

        return parent::getINbrPrestaMaNew();
    }

    /**
     * {@inheritDoc}
     */
    public function setINbrLirMarocains($iNbrLirMarocains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINbrLirMarocains', [$iNbrLirMarocains]);

        return parent::setINbrLirMarocains($iNbrLirMarocains);
    }

    /**
     * {@inheritDoc}
     */
    public function getINbrLirMarocains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINbrLirMarocains', []);

        return parent::getINbrLirMarocains();
    }

    /**
     * {@inheritDoc}
     */
    public function setIParcMarocIpv4Afrinic($iParcMarocIpv4Afrinic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIParcMarocIpv4Afrinic', [$iParcMarocIpv4Afrinic]);

        return parent::setIParcMarocIpv4Afrinic($iParcMarocIpv4Afrinic);
    }

    /**
     * {@inheritDoc}
     */
    public function getIParcMarocIpv4Afrinic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIParcMarocIpv4Afrinic', []);

        return parent::getIParcMarocIpv4Afrinic();
    }

    /**
     * {@inheritDoc}
     */
    public function setIStockIpv4Afrinic($iStockIpv4Afrinic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIStockIpv4Afrinic', [$iStockIpv4Afrinic]);

        return parent::setIStockIpv4Afrinic($iStockIpv4Afrinic);
    }

    /**
     * {@inheritDoc}
     */
    public function getIStockIpv4Afrinic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIStockIpv4Afrinic', []);

        return parent::getIStockIpv4Afrinic();
    }

    /**
     * {@inheritDoc}
     */
    public function setINbrIpv4Allouees($iNbrIpv4Allouees)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINbrIpv4Allouees', [$iNbrIpv4Allouees]);

        return parent::setINbrIpv4Allouees($iNbrIpv4Allouees);
    }

    /**
     * {@inheritDoc}
     */
    public function getINbrIpv4Allouees()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINbrIpv4Allouees', []);

        return parent::getINbrIpv4Allouees();
    }

    /**
     * {@inheritDoc}
     */
    public function setIRepartIpv4LirMaroc($iRepartIpv4LirMaroc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIRepartIpv4LirMaroc', [$iRepartIpv4LirMaroc]);

        return parent::setIRepartIpv4LirMaroc($iRepartIpv4LirMaroc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIRepartIpv4LirMaroc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIRepartIpv4LirMaroc', []);

        return parent::getIRepartIpv4LirMaroc();
    }

    /**
     * {@inheritDoc}
     */
    public function setIEtatEpuisIpv4($iEtatEpuisIpv4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIEtatEpuisIpv4', [$iEtatEpuisIpv4]);

        return parent::setIEtatEpuisIpv4($iEtatEpuisIpv4);
    }

    /**
     * {@inheritDoc}
     */
    public function getIEtatEpuisIpv4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIEtatEpuisIpv4', []);

        return parent::getIEtatEpuisIpv4();
    }

    /**
     * {@inheritDoc}
     */
    public function setIPlageIpv6Maroc($iPlageIpv6Maroc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIPlageIpv6Maroc', [$iPlageIpv6Maroc]);

        return parent::setIPlageIpv6Maroc($iPlageIpv6Maroc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIPlageIpv6Maroc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIPlageIpv6Maroc', []);

        return parent::getIPlageIpv6Maroc();
    }

}
