<?php

namespace Proxies\__CG__\Ictdata\IctdataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class D_parc_abonne extends \Ictdata\IctdataBundle\Entity\D_parc_abonne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pMobilePostPaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pMobilePrePaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeMobiliteRestreinte', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeResidentiel', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeProfessionnel', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeGlobal', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pPubliphoneLignes', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetGlobaleAdsl', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetGlobaleMobile', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetGlobaleAutre', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetBasdebit', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternet', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pNomDomainMa', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pRepartMa', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pRepartAutre', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pNewEnregistTrimestre'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pMobilePostPaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pMobilePrePaye', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeMobiliteRestreinte', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeResidentiel', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeProfessionnel', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pFixeGlobal', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pPubliphoneLignes', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetGlobaleAdsl', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetGlobaleMobile', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetGlobaleAutre', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternetBasdebit', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pInternet', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pNomDomainMa', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pRepartMa', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pRepartAutre', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_parc_abonne' . "\0" . 'pNewEnregistTrimestre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (D_parc_abonne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPDate($pDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPDate', [$pDate]);

        return parent::setPDate($pDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDate', []);

        return parent::getPDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPMobilePostPaye($pMobilePostPaye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPMobilePostPaye', [$pMobilePostPaye]);

        return parent::setPMobilePostPaye($pMobilePostPaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getPMobilePostPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPMobilePostPaye', []);

        return parent::getPMobilePostPaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setPMobilePrePaye($pMobilePrePaye)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPMobilePrePaye', [$pMobilePrePaye]);

        return parent::setPMobilePrePaye($pMobilePrePaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getPMobilePrePaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPMobilePrePaye', []);

        return parent::getPMobilePrePaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setPFixeMobiliteRestreinte($pFixeMobiliteRestreinte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPFixeMobiliteRestreinte', [$pFixeMobiliteRestreinte]);

        return parent::setPFixeMobiliteRestreinte($pFixeMobiliteRestreinte);
    }

    /**
     * {@inheritDoc}
     */
    public function getPFixeMobiliteRestreinte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPFixeMobiliteRestreinte', []);

        return parent::getPFixeMobiliteRestreinte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPFixeResidentiel($pFixeResidentiel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPFixeResidentiel', [$pFixeResidentiel]);

        return parent::setPFixeResidentiel($pFixeResidentiel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPFixeResidentiel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPFixeResidentiel', []);

        return parent::getPFixeResidentiel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPFixeProfessionnel($pFixeProfessionnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPFixeProfessionnel', [$pFixeProfessionnel]);

        return parent::setPFixeProfessionnel($pFixeProfessionnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPFixeProfessionnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPFixeProfessionnel', []);

        return parent::getPFixeProfessionnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPFixeGlobal($pFixeGlobal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPFixeGlobal', [$pFixeGlobal]);

        return parent::setPFixeGlobal($pFixeGlobal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPFixeGlobal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPFixeGlobal', []);

        return parent::getPFixeGlobal();
    }

    /**
     * {@inheritDoc}
     */
    public function setPPubliphoneLignes($pPubliphoneLignes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPPubliphoneLignes', [$pPubliphoneLignes]);

        return parent::setPPubliphoneLignes($pPubliphoneLignes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPPubliphoneLignes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPPubliphoneLignes', []);

        return parent::getPPubliphoneLignes();
    }

    /**
     * {@inheritDoc}
     */
    public function setPInternetGlobaleAdsl($pInternetGlobaleAdsl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPInternetGlobaleAdsl', [$pInternetGlobaleAdsl]);

        return parent::setPInternetGlobaleAdsl($pInternetGlobaleAdsl);
    }

    /**
     * {@inheritDoc}
     */
    public function getPInternetGlobaleAdsl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPInternetGlobaleAdsl', []);

        return parent::getPInternetGlobaleAdsl();
    }

    /**
     * {@inheritDoc}
     */
    public function setPInternetGlobaleMobile($pInternetGlobaleMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPInternetGlobaleMobile', [$pInternetGlobaleMobile]);

        return parent::setPInternetGlobaleMobile($pInternetGlobaleMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getPInternetGlobaleMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPInternetGlobaleMobile', []);

        return parent::getPInternetGlobaleMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setPInternetGlobaleAutre($pInternetGlobaleAutre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPInternetGlobaleAutre', [$pInternetGlobaleAutre]);

        return parent::setPInternetGlobaleAutre($pInternetGlobaleAutre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPInternetGlobaleAutre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPInternetGlobaleAutre', []);

        return parent::getPInternetGlobaleAutre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPInternetBasdebit($pInternetBasdebit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPInternetBasdebit', [$pInternetBasdebit]);

        return parent::setPInternetBasdebit($pInternetBasdebit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPInternetBasdebit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPInternetBasdebit', []);

        return parent::getPInternetBasdebit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPInternet($pInternet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPInternet', [$pInternet]);

        return parent::setPInternet($pInternet);
    }

    /**
     * {@inheritDoc}
     */
    public function getPInternet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPInternet', []);

        return parent::getPInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPNomDomainMa($pNomDomainMa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPNomDomainMa', [$pNomDomainMa]);

        return parent::setPNomDomainMa($pNomDomainMa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPNomDomainMa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPNomDomainMa', []);

        return parent::getPNomDomainMa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPRepartMa($pRepartMa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPRepartMa', [$pRepartMa]);

        return parent::setPRepartMa($pRepartMa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPRepartMa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPRepartMa', []);

        return parent::getPRepartMa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPRepartAutre($pRepartAutre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPRepartAutre', [$pRepartAutre]);

        return parent::setPRepartAutre($pRepartAutre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPRepartAutre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPRepartAutre', []);

        return parent::getPRepartAutre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPNewEnregistTrimestre($pNewEnregistTrimestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPNewEnregistTrimestre', [$pNewEnregistTrimestre]);

        return parent::setPNewEnregistTrimestre($pNewEnregistTrimestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPNewEnregistTrimestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPNewEnregistTrimestre', []);

        return parent::getPNewEnregistTrimestre();
    }

}
