<?php

namespace Proxies\__CG__\Ictdata\IctdataBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class D_part_marche extends \Ictdata\IctdataBundle\Entity\D_part_marche implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePostIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePreIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePostMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePreMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePostWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePreWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeResidIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeProfIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeResidMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeProfMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeResidWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeProfWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcLignesPubliIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcLignesPubliMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetAdslIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetMobileIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetAdslMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetMobileMed'];
        }

        return ['__isInitialized__', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'id', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partDate', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePostIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePreIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePostMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePreMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePostWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcMobilePreWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeResidIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeProfIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeResidMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeProfMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeResidWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcFixeProfWana', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcLignesPubliIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcLignesPubliMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetAdslIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetMobileIam', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetAdslMed', '' . "\0" . 'Ictdata\\IctdataBundle\\Entity\\D_part_marche' . "\0" . 'partParcInternetMobileMed'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (D_part_marche $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartDate($partDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartDate', [$partDate]);

        return parent::setPartDate($partDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartDate', []);

        return parent::getPartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcMobilePostIam($partParcMobilePostIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcMobilePostIam', [$partParcMobilePostIam]);

        return parent::setPartParcMobilePostIam($partParcMobilePostIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcMobilePostIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcMobilePostIam', []);

        return parent::getPartParcMobilePostIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcMobilePreIam($partParcMobilePreIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcMobilePreIam', [$partParcMobilePreIam]);

        return parent::setPartParcMobilePreIam($partParcMobilePreIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcMobilePreIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcMobilePreIam', []);

        return parent::getPartParcMobilePreIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcMobilePostMed($partParcMobilePostMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcMobilePostMed', [$partParcMobilePostMed]);

        return parent::setPartParcMobilePostMed($partParcMobilePostMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcMobilePostMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcMobilePostMed', []);

        return parent::getPartParcMobilePostMed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcMobilePreMed($partParcMobilePreMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcMobilePreMed', [$partParcMobilePreMed]);

        return parent::setPartParcMobilePreMed($partParcMobilePreMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcMobilePreMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcMobilePreMed', []);

        return parent::getPartParcMobilePreMed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcMobilePostWana($partParcMobilePostWana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcMobilePostWana', [$partParcMobilePostWana]);

        return parent::setPartParcMobilePostWana($partParcMobilePostWana);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcMobilePostWana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcMobilePostWana', []);

        return parent::getPartParcMobilePostWana();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcMobilePreWana($partParcMobilePreWana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcMobilePreWana', [$partParcMobilePreWana]);

        return parent::setPartParcMobilePreWana($partParcMobilePreWana);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcMobilePreWana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcMobilePreWana', []);

        return parent::getPartParcMobilePreWana();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcFixeResidIam($partParcFixeResidIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcFixeResidIam', [$partParcFixeResidIam]);

        return parent::setPartParcFixeResidIam($partParcFixeResidIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcFixeResidIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcFixeResidIam', []);

        return parent::getPartParcFixeResidIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcFixeProfIam($partParcFixeProfIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcFixeProfIam', [$partParcFixeProfIam]);

        return parent::setPartParcFixeProfIam($partParcFixeProfIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcFixeProfIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcFixeProfIam', []);

        return parent::getPartParcFixeProfIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcFixeResidMed($partParcFixeResidMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcFixeResidMed', [$partParcFixeResidMed]);

        return parent::setPartParcFixeResidMed($partParcFixeResidMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcFixeResidMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcFixeResidMed', []);

        return parent::getPartParcFixeResidMed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcFixeProfMed($partParcFixeProfMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcFixeProfMed', [$partParcFixeProfMed]);

        return parent::setPartParcFixeProfMed($partParcFixeProfMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcFixeProfMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcFixeProfMed', []);

        return parent::getPartParcFixeProfMed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcFixeResidWana($partParcFixeResidWana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcFixeResidWana', [$partParcFixeResidWana]);

        return parent::setPartParcFixeResidWana($partParcFixeResidWana);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcFixeResidWana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcFixeResidWana', []);

        return parent::getPartParcFixeResidWana();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcFixeProfWana($partParcFixeProfWana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcFixeProfWana', [$partParcFixeProfWana]);

        return parent::setPartParcFixeProfWana($partParcFixeProfWana);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcFixeProfWana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcFixeProfWana', []);

        return parent::getPartParcFixeProfWana();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcLignesPubliIam($partParcLignesPubliIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcLignesPubliIam', [$partParcLignesPubliIam]);

        return parent::setPartParcLignesPubliIam($partParcLignesPubliIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcLignesPubliIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcLignesPubliIam', []);

        return parent::getPartParcLignesPubliIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcLignesPubliMed($partParcLignesPubliMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcLignesPubliMed', [$partParcLignesPubliMed]);

        return parent::setPartParcLignesPubliMed($partParcLignesPubliMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcLignesPubliMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcLignesPubliMed', []);

        return parent::getPartParcLignesPubliMed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcInternetAdslIam($partParcInternetAdslIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcInternetAdslIam', [$partParcInternetAdslIam]);

        return parent::setPartParcInternetAdslIam($partParcInternetAdslIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcInternetAdslIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcInternetAdslIam', []);

        return parent::getPartParcInternetAdslIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcInternetMobileIam($partParcInternetMobileIam)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcInternetMobileIam', [$partParcInternetMobileIam]);

        return parent::setPartParcInternetMobileIam($partParcInternetMobileIam);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcInternetMobileIam()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcInternetMobileIam', []);

        return parent::getPartParcInternetMobileIam();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcInternetAdslMed($partParcInternetAdslMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcInternetAdslMed', [$partParcInternetAdslMed]);

        return parent::setPartParcInternetAdslMed($partParcInternetAdslMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcInternetAdslMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcInternetAdslMed', []);

        return parent::getPartParcInternetAdslMed();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartParcInternetMobileMed($partParcInternetMobileMed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartParcInternetMobileMed', [$partParcInternetMobileMed]);

        return parent::setPartParcInternetMobileMed($partParcInternetMobileMed);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartParcInternetMobileMed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartParcInternetMobileMed', []);

        return parent::getPartParcInternetMobileMed();
    }

}
