d_part_marche:
    path:     /
    defaults: { _controller: "IctdataBundle:D_part_marche:index" }

d_part_marche_show:
    path:     /{id}/show
    defaults: { _controller: "IctdataBundle:D_part_marche:show" }

d_part_marche_new:
    path:     /new
    defaults: { _controller: "IctdataBundle:D_part_marche:new" }

d_part_marche_create:
    path:     /create
    defaults: { _controller: "IctdataBundle:D_part_marche:create" }
    methods:  POST

d_part_marche_edit:
    path:     /{id}/edit
    defaults: { _controller: "IctdataBundle:D_part_marche:edit" }

d_part_marche_update:
    path:     /{id}/update
    defaults: { _controller: "IctdataBundle:D_part_marche:update" }
    methods:  [POST, PUT]

d_part_marche_delete:
    path:     /{id}/delete
    defaults: { _controller: "IctdataBundle:D_part_marche:delete" }
    methods:  [POST, DELETE]
