<?php

namespace Ictdata\IctdataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * D_infrastruct_autreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class D_infrastruct_autreRepository extends EntityRepository
{
}
