<?php

namespace Ictdata\IctdataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * E_enqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class E_enqueteRepository extends EntityRepository
{
public function findByAuthorAndDate($author, $year)
        {
            $qb = $this->createQueryBuilder('e');
            $qb->where('e.author = :author')
                ->setParameter('author', $author)
                ->andWhere('e.date < :year')
                ->setParameter('year', $year)
                ->orderBy('e.date', 'DESC');
            return $qb
                ->getQuery()
                ->getResult()
                ;
        }
}
