<?php

namespace Ictdata\IctdataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * E_enqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class E_enqueteRepository extends EntityRepository
{
}
